# Generated by Django 4.1 on 2023-03-20 01:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0001_initial"),
        ("authenticate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Scheduled"),
                            (2, "Confirmed"),
                            (3, "Canceled"),
                            (4, "Finished"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 3, 19, 22, 36, 43, 538301)
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_return", models.BooleanField(default=False)),
                ("day_off", models.BooleanField(default=False)),
                ("off_reason", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.clinic",
                    ),
                ),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinical.desk"
                    ),
                ),
                (
                    "pacient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical.pacient",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule_event",
                "verbose_name_plural": "schedule_events",
                "db_table": "schedule_event",
            },
        ),
    ]
