# Generated by Django 4.1 on 2023-03-20 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleevent",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 19, 22, 38, 57, 75724)
            ),
        ),
    ]
