# Generated by Django 4.1 on 2023-03-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plus_planner.utils.overwrite_image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "taxpayer_identification",
                    models.CharField(max_length=13, unique=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=plus_planner.utils.overwrite_image.OverwriteImage(),
                        upload_to=plus_planner.utils.overwrite_image.upload_to,
                    ),
                ),
                ("is_clinic", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "taxpayer_identification",
                    models.CharField(max_length=20, unique=True),
                ),
                ("subsidiary", models.BooleanField(default=False)),
                ("natural_person", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "clinic",
                "verbose_name_plural": "clinics",
                "db_table": "clinic",
            },
        ),
        migrations.CreateModel(
            name="ClinicUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Manager"),
                            (2, "Doctor"),
                            (3, "Assistant"),
                            (4, "Nurse"),
                        ]
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plus_planner.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "clinic_role",
                "verbose_name_plural": "clinic_roles",
                "db_table": "clinic_role",
            },
        ),
        migrations.AddField(
            model_name="clinic",
            name="account",
            field=models.ManyToManyField(
                through="plus_planner.ClinicUserRole", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
