# Generated by Django 4.1 on 2023-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plus_planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicuserrole",
            name="role_type",
            field=models.SmallIntegerField(
                choices=[(1, "Manager"), (2, "Doctor"), (3, "Assistant"), (4, "Nurse")]
            ),
        ),
    ]
