# Generated by Django 4.1 on 2023-03-07 01:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("plus_planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("vacation", models.BooleanField(default=True)),
                ("observation", models.CharField(max_length=150)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plus_planner.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "desk",
                "verbose_name_plural": "desks",
                "db_table": "desk",
            },
        ),
        migrations.CreateModel(
            name="Pacient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("taxypayer_identification", models.CharField(max_length=13)),
                ("birth_date", models.DateField()),
                (
                    "genre",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Male"), (2, "Famale"), (3, "other")]
                    ),
                ),
            ],
            options={
                "verbose_name": "pacient",
                "verbose_name_plural": "pacient",
                "db_table": "pacient",
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Scheduled"),
                            (2, "Confirmed"),
                            (3, "Canceled"),
                            (4, "Finished"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 3, 6, 22, 23, 32, 227649)
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_return", models.BooleanField(default=False)),
                ("day_off", models.BooleanField(default=False)),
                ("off_reason", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plus_planner.clinic",
                    ),
                ),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plus_planner.desk",
                    ),
                ),
                (
                    "pacient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plus_planner.pacient",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule_event",
                "verbose_name_plural": "schedule_events",
                "db_table": "schedule_event",
            },
        ),
    ]
