# Generated by Django 3.2 on 2023-06-14 00:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(99999999)])),
                ('name', models.CharField(max_length=50)),
                ('validity', models.DateField(null=True)),
                ('trail', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='LicenseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(null=True)),
                ('off_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_license', to='billing.license')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(null=True)),
                ('user_license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='billing.licenseuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
