# Generated by Django 3.2 on 2023-06-14 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=50)),
                ('taxypayer_identification', models.CharField(max_length=13)),
                ('birth_date', models.DateField()),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale'), (3, 'other')])),
            ],
            options={
                'verbose_name': 'pacient',
                'verbose_name_plural': 'pacient',
                'db_table': 'pacient',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(default='', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.CharField(default='', max_length=50)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.pacient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.treatment')),
            ],
            options={
                'verbose_name': 'urgency',
                'verbose_name_plural': 'urgences',
                'db_table': 'urgency',
            },
        ),
        migrations.AddField(
            model_name='pacient',
            name='treatments',
            field=models.ManyToManyField(to='clinical.Treatment'),
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('vacation', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=150)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.clinic')),
            ],
            options={
                'verbose_name': 'desk',
                'verbose_name_plural': 'desks',
                'db_table': 'desk',
            },
        ),
    ]
