# Generated by Django 3.2 on 2023-04-10 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tenant_schemas.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=50)),
                ('taxypayer_identification', models.CharField(max_length=13)),
                ('birth_date', models.DateField()),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale'), (3, 'other')])),
            ],
            options={
                'verbose_name': 'pacient',
                'verbose_name_plural': 'pacient',
                'db_table': 'pacient',
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('vacation', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=150)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.clinic')),
            ],
            options={
                'verbose_name': 'desk',
                'verbose_name_plural': 'desks',
                'db_table': 'desk',
            },
        ),
    ]
