# Generated by Django 4.1 on 2023-03-20 01:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pacient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("taxypayer_identification", models.CharField(max_length=13)),
                ("birth_date", models.DateField()),
                (
                    "genre",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Male"), (2, "Famale"), (3, "other")]
                    ),
                ),
            ],
            options={
                "verbose_name": "pacient",
                "verbose_name_plural": "pacient",
                "db_table": "pacient",
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("vacation", models.BooleanField(default=True)),
                ("observation", models.CharField(max_length=150)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "desk",
                "verbose_name_plural": "desks",
                "db_table": "desk",
            },
        ),
    ]
