# Generated by Django 3.2 on 2023-06-14 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.license'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='account',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='authenticate.clinic'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.license'),
        ),
    ]
