"""
Project constants
"""
# Account

USER = 1
BILLING = 2
CLINICAL = 3
EXTRA = 4
FINANCY = 5
MARKETING = 6
SCHEDULER = 7


STR_USER = "user"
STR_BILLING = "billing"
STR_CLINICAL = "clinical"
STR_EXTRA = "extra"
STR_FINANCY = "financy"
STR_MARKETING = "marketing"
STR_SCHEDULER = "scheduler"

DICT_MODULE_TO_STRING = {
    USER: STR_USER,
    BILLING: STR_BILLING,
    CLINICAL: STR_CLINICAL,
    EXTRA: STR_EXTRA,
    FINANCY: STR_FINANCY,
    MARKETING: STR_MARKETING,
    SCHEDULER: STR_SCHEDULER,
}


# Schedule

SCHEDULED = 1
CONFIRMED = 2
CANCELED = 3
FINISHED = 4

STR_SCHEDULED = "Scheduled"
STR_CONFIRMED = "Confirmed"
STR_CANCELED = "Canceled"
STR_FINISHED = "Finished"

# Clinical
MALE = 1
FAMALE = 2
OTHER = 3

STR_MALE = "Male"
STR_FAMALE = "Famale"
STR_OTHER = "other"


MIN_LICENSE_CODE = 10000000
MAX_LICENSE_CODE = 99999999

MIN_CLINIC_CODE = 10000
MAX_CLINIC_CODE = 99999
